/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs/$programId'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs/$programId/index'
import { Route as ProgramsProgramIdWorkoutsWorkoutIdRouteImport } from './routes/programs/$programId/workouts/$workoutId'

const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsProgramIdRoute,
} as any)
const ProgramsProgramIdWorkoutsWorkoutIdRoute =
  ProgramsProgramIdWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => ProgramsProgramIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/workouts/$workoutId': typeof ProgramsProgramIdWorkoutsWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/workouts/$workoutId': typeof ProgramsProgramIdWorkoutsWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/workouts/$workoutId': typeof ProgramsProgramIdWorkoutsWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/programs/$programId'
    | '/programs/$programId/'
    | '/programs/$programId/workouts/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/programs/$programId'
    | '/programs/$programId/workouts/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/programs/$programId'
    | '/programs/$programId/'
    | '/programs/$programId/workouts/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
    '/programs/$programId/workouts/$workoutId': {
      id: '/programs/$programId/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/programs/$programId/workouts/$workoutId'
      preLoaderRoute: typeof ProgramsProgramIdWorkoutsWorkoutIdRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
  }
}

interface ProgramsProgramIdRouteChildren {
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
  ProgramsProgramIdWorkoutsWorkoutIdRoute: typeof ProgramsProgramIdWorkoutsWorkoutIdRoute
}

const ProgramsProgramIdRouteChildren: ProgramsProgramIdRouteChildren = {
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
  ProgramsProgramIdWorkoutsWorkoutIdRoute:
    ProgramsProgramIdWorkoutsWorkoutIdRoute,
}

const ProgramsProgramIdRouteWithChildren =
  ProgramsProgramIdRoute._addFileChildren(ProgramsProgramIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
